### ISSUE TITLE
ModuleNotFoundError: No module named 'DWonder.SEG3DUnet'

### ISSUE THREAD

**Issue by mk-mccann** [yuanlong-o/Deep_widefield_cal_inferece#2]
After installing DeepWonder from pip, I run into the following error:

```
File "main_RSM.py", line 19, in <module>
    from DWonder.SEG3DUnet import seg_3dunet
ModuleNotFoundError: No module named 'DWonder.SEG3DUnet'
```

It looks like the file ```SEG3DUnet.py``` doesn't install properly.

**Comment by yuanlong-o** [comment]
Sorry for the inconvenience. We are investigating this error now. Will update shortly

**Comment by yuanlong-o** [comment]
Sorry for the delay. We sincerely apologize since the original repo was made almost one and a half years ago and many things have changed. Could you please try a zipped file, DeepWonder/deepeonder_oldversion.zip, which has been uploaded to this repo recently? It contains some original codes and .pth that we've tested in our lab. If you have further questions or comments pls let me know. If it can work we can fix the repo based on that .zip file.

**Comment by mk-mccann** [comment]
I'll give it a go. Are the installation requirements the same as listed in the README?

**Comment by yuanlong-o** [comment]
Yes they are the same.

**Comment by mk-mccann** [comment]
I was successful in making the old version run on a WSL2 Ubuntu installation. Hopefully that helps get the pip package sorted out.

Thanks for your help!

**Comment by yuanlong-o** [comment]
Great！

**Comment by SofiaTorchia** [comment]
Hello, I followed the instruction on the readme and I am getting the same error as the one posted at the beginning in this issue:
```
(deepwonder_env) python script.py
Traceback (most recent call last):
  File "main_RSM.py", line 19, in <module>
    from DWonder.SEG3DUnet import seg_3dunet
ModuleNotFoundError: No module named 'DWonder.SEG3DUnet'
(deepwonder_env)
```
